//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from c:/Users/azazi/Desktop/GameInitialization/Game/src/ANTLR grammar/Game.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="GameParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.CLSCompliant(false)]
public interface IGameVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="GameParser.game"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGame([NotNull] GameParser.GameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GameParser.initGame"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInitGame([NotNull] GameParser.InitGameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GameParser.objectWithProperty"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitObjectWithProperty([NotNull] GameParser.ObjectWithPropertyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GameParser.objectProperties"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitObjectProperties([NotNull] GameParser.ObjectPropertiesContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GameParser.property"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProperty([NotNull] GameParser.PropertyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GameParser.chainOfCommands"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitChainOfCommands([NotNull] GameParser.ChainOfCommandsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GameParser.simplecommand"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSimplecommand([NotNull] GameParser.SimplecommandContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GameParser.conditioncommand"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConditioncommand([NotNull] GameParser.ConditioncommandContext context);
}
